### PR TITLE
Add StorageContentGet function

### PR DESCRIPTION
**Pull request by alperencelik**
This PR tries to add a function to get all existing content from node's specified storage. 

The following API documentation:

https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/storage/{storage}/content

### CODE REVIEW

**Comment by alperencelik** [comment]
IMO, there is still an option to get content by type but in my use case I would like to get all contents and filter by filename so I thought adding this function might be a proper implementation.

**Comment by luthermonson** [comment]
Would this be better as a receiver on Storage and in [this file](https://github.com/luthermonson/go-proxmox/blob/main/storage.go)?

**Comment by alperencelik** [comment]
> Would this be better as a receiver on Storage and in [this file](https://github.com/luthermonson/go-proxmox/blob/main/storage.go)?

That makes more sense to me as well so updated accordingly.

**Review by luthermonson — APPROVED** [review]

**Comment by luthermonson** [comment]
thanks for the pr! i cut a beta3 in case you need this and want to pin to something

**Pull request merged**
