### PR TITLE
Extend cloud-init ISO builder to include vendor-data and network-config

### PR DESCRIPTION
**Pull request by jqueuniet**
Current implementation is missing support for vendor-data and network-config.

Vendor data is similar to user-data, but allows a clean separation of cloud-config scripts from infrastructure providers and clients. Network config is basically a netplan config file and is the recommended way to setup networking use-cases different from the default cloud-init behavior (DHCP on the first working interface).

### CODE REVIEW

**Comment by luthermonson** [comment]
https://cloudinit.readthedocs.io/en/latest/reference/datasources/nocloud.html#file-formats says vendor data is supported, is network config just not documented? if it works np to merge this

**Comment by luthermonson** [comment]
welp there it is: https://cloudinit.readthedocs.io/en/latest/reference/datasources/nocloud.html#example-meta-data

it is supported. answered my own question

**Comment by jqueuniet** [comment]
network-config is how PVE is implementing the various network cloud-init properties on virtual machines like `nameservers`, `searchdomains` or `ipconfigX` for the nocloud datasource.

**Comment by mcbenjemaa** [comment]
@jqueuniet I tested the network-config with this iso mechansinm but it doesn't work

**Comment by jqueuniet** [comment]
I'm sorry to hear that, but I'm not sure an old closed PR is the best place to talk about this. Could you open a new issue and provide a sample non-working ISO file, the network-config string provided, the overall network setup used for PVE and the VM configuration?

**Comment by mcbenjemaa** [comment]
I tested it. 

Great!
I tested the network-config and it worked ✅

´´´yaml
network:
  version: 2
  renderer: networkd
  ethernets:
    eth0:
      match:
        name: en*
      dhcp4: 'no'
      addresses:
        - 10.10.10.17/24
      routes:
        - to: default
          via: 10.10.10.1
      nameservers:
        addresses:
          - 8.8.8.8
          - 8.8.4.4
´´´

Thanks

**Comment by mcbenjemaa** [comment]
Do you know how to set the hostname via metadata?

As it doesn't work for me!

**Comment by luthermonson** [comment]
what did you try? i think you're supposed to use `local-hostname` in the metadata file but that's just what i've learned from reading docs which might be old

**Comment by jqueuniet** [comment]
I'm using the `fqdn` field in vendor-data for that at the moment.

https://cloudinit.readthedocs.io/en/latest/reference/modules.html#set-hostname

**Comment by mcbenjemaa** [comment]
Oh, well. 
For local-hostname, it works. 

For fqdn, 
I have to try.

**Comment by mcbenjemaa** [comment]
We are building the capi provider for proxmox. 

And we are relying on this client. 
So, we are supporting it.

Thanks for your help.

**Comment by luthermonson** [comment]
lol everyone is working on a capi provider then, there are 2 more already started. keep it up! let's get one good one eventually :)

**Comment by luthermonson** [comment]
join us in the slack channel by the way if you want more realtime support: https://gophers.slack.com/archives/C05920LDDD3

**Comment by luthermonson** [comment]
good! keep working hard

**Comment by mcbenjemaa** [comment]
btw, do you know if we can use bios uuid as a unique identifier for machines accros proxmox nodes?

**Comment by luthermonson** [comment]
better to have a thread on in the slack channel if you don't mind, come over there and pose the question and let's start a thread about it

**Comment by mcbenjemaa** [comment]
i can't join with that link :)

**Comment by luthermonson** [comment]
try this https://gophers.slack.com/archives/C05920LDDD3

**Comment by mcbenjemaa** [comment]
mc.benjemaa@gmail.com doesn’t have an account on this workspace.

**Comment by luthermonson** [comment]
make one! it's free

**Pull request merged**
