### PR TITLE
feat: add resize, unlink and migrate qemu calls

### PR DESCRIPTION
**Pull request by jqueuniet**
Add methods to facilitate VM migrations, disk resize and disk removal.

### CODE REVIEW

**Comment by luthermonson** [comment]
closes #39

**Comment by jqueuniet** [comment]
Sorry, I might have come across as confusing opening two different discussions on similar subjects at once, but #39 is an open question on existing API methods (`clone` and `move_disk`), not related to this PR which is implementing new methods (`resize`, `unlink` and `migrate`) where there shouldn't be any compatibility issue.

**Comment by luthermonson** [comment]
yup i figured it out after i actually read it ;) i love the suggestions and just commented. this PR is good to merge

**Comment by luthermonson** [comment]
thanks for the contribution! @jqueuniet

**Pull request merged**
