### PR TITLE
Add support for download-url function on node/storage

### PR DESCRIPTION
**Pull request by alperencelik**
The PR aims to add download-url functionality on Proxmox API. Here is the relevant API documentation:

https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/storage/{storage}/download-url

### CODE REVIEW

**Comment by alperencelik** [comment]
I'm not good at naming so I'm open to any ideas for renaming the function.

**Comment by luthermonson** [comment]
> I'm not good at naming so I'm open to any ideas for renaming the function.

this api endpoint downloads the url to the storage, i think `StorageDownloadURL` is probably fine and matches the proxmox api

if motivated there are optional params which i think others could find super useful, might be better to refactor and make a DownloadURLOptions struct which you build the post params from and add the optional params

**Comment by alperencelik** [comment]
Thanks for the review! I think adding a struct for covering optional parameters is good idea.

**Review by luthermonson — APPROVED** [review]

**Comment by luthermonson** [comment]
good work!

**Pull request merged**
